services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      APP_ENV: ${APP_ENV}
      PORT: 8080
      BLUEPRINT_DB_URL: ./db/test.db
    volumes:
      - sqlite_bp:/app/db
volumes:
  sqlite_bp:
